name: Run tests

on:
  pull_request:
    branches: [main, release]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Test NormJS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.6.0

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
