name: Run tests

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  season_semester: SPRING
  season_year: 2022

jobs:
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.6.0

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    container:
      image: postgres:latest
      options: --name uncc_six_mans
      ports:
        - 5432:5432
      env:
        POSTGRES_USER: Norm
        POSTGRES_PASSWORD: NormTheNiner

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.6.0

      - name: Install dependencies
        run: npm install

      - name: Push Prisma schema
        run: npx prisma db push

      - name: Run Tests
        run: npm run integration
